version: '3.8'
services:
  dev-db:
    image: postgres:13
    ports:
      - 5434:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: ntic
    networks:
      - freecodecamp
networks:
  freecodecamp:

#to launch our database we need to run docker-compose up -d from the root of our project
#docker compose up DB-NAME -d
#-d means that we want to run it in the background
#with docker ps command, we can see that our database is running
#to see the logs, copy the name of the container under container ID and run docker logs CONTAINER-ID
